# control dark mode: auto | dark | toggle
mode = "toggle"

# The URL the site will be built for
base_url = "https://dunateo.github.io/"

# The site title and description; used in feeds by default.
title = "Superthévenin Blog"
description = "Superthévenin personal website for various notes and ideas"

# The default language; used in feeds.
default_language = "en"

# The site theme to use.
theme = "archie-zola"

# For overriding the default ouput directory `public`, set it to another value (e.g.: "docs")
output_dir = "public"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# if set true, will use external CDN resource to load font and js file
useCDN = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

copyright = "Dunateo"

[extra.translations]
languages = [{name = "en", url = "/"}]

# config social icon info in the footer
[[extra.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/XXXMrG/archie-zola"

[[extra.social]]
icon = "twitter"
name = "Twitter"
url = "https://github.com/your-name/"

[[extra.social]]
icon = "gitlab"
name = "GitLab"
url = "https://gitlab.com/your-name/"

